### PR TITLE
Updates for Protect 3.0.22

### PR DESCRIPTION
**Pull request by AngellusMortis**
* Adds new helpers for new logic around IRLEDMode and HDRMode
* Adds deprecation warning for `set_hdr` (use `set_hdr_mode` instead)
* Updates models for UniFi Protect 3.0.22 (**breaking**, but _should_ still work with 2.x)

Model Changes:

Bootstrap:

* Removes `displays` and `legacyUFVs`

NVR:

* Removes `camera_tcp` port
* Adds `ai_feature_console` port
* Adds fields for `smart_detection` and `is_ucore_stacked`

Camera:

* Adds new camera channel settings: `auto_bitrate`, `auto_fps` and `bitrate`
* Adds new ISP settings: `hdr_mode`, `icr_custom_value`, `icr_switch_mode` and `spotlight_detection`
* Removes `has_battery`
* Removes PIR Settings

Chime:

* Adds fields `has_https_client_ota`, `platform`, `repeat_times`, `track_no`, `ring_settings`, and `speaker_track_list`

### CODE REVIEW

**Comment by bdraco** [comment]
I'll give it a shot on my prod just to check for regressions with older versions (seems unlikely)

**Comment by AngellusMortis** [comment]
There is not going to be much to test yet. I need to update HA with how the IRLEDMode and HDRMode works so it can be tested again a 2.x version easily. 

Otherwise, you have to call `set_hdr_mode` manually from the shell to test it.

**Comment by bdraco** [comment]
small system with 2.x ok

testing on the large prod one now

**Review by bdraco — APPROVED** [review]
Tested on my large production 2.x install 👍

**Pull request merged**
