### PR TITLE
Fixes some edge cases

### PR DESCRIPTION
**Pull request by AngellusMortis**
* Reduces the amount of events that are pulled by default to only 1 hour worth
* Do not try to cast a type that is already the correct type
* Do not fail generating sample data if smart track is missing
* Handle Protect bug where sometimes `start`/`end` query parameters are not applied correctly, emit warning to user that their query is also taking longer then expected
* More logging for handling events
* Fixes edge case where user's email can be `None`

### CODE REVIEW

**Comment by bdraco** [comment]
Tested on one production system and didn't observe any issues or regressions.

Trying another one now

**Comment by bdraco** [comment]
Screenshot 2023-12-30 at 2 44 23 PM
Screenshot 2023-12-30 at 2 44 19 PM


Saw some unexpected places on the profile but I don't think they are new

**Comment by AngellusMortis** [comment]
That looks like it is overall better though since it should not be calling `get_events` if the WS is working.

**Comment by bdraco** [comment]
I think we can make `bootstrap_models` a tuple so it doesn't get recreated every time its called

**Review by bdraco — APPROVED** [review]
Testing looks good on the 2nd system as well

**Comment by bdraco** [comment]
Trying the tuple change now. If it works I'll send a PR in a moment

**Pull request merged**
