### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by pizzaboy192**
Ubiquiti confirmed that facial recognition is not done on the cloud (via https://community.ui.com/questions/Does-Facial-Recognition-require-internet-access-to-work-or-is-it-run-locally-on-the-recorder-or-cam/4b9f2bbc-6f65-422e-848d-1d2489f29228#answer/4826df3e-c8bf-4686-9d55-76eba3ab97ad ) 

Removing inaccurate claim from readme to prevent misinformation from being spread.

### CODE REVIEW

**Comment by AngellusMortis** [comment]
Enabling Smart Detection both still requires an Ubiquiti account _and_ Remote Access to be enabled. Until both requirements are removed, the README is not inaccurate. 

Local only features need to stay local only. They should not require an Ubiquiti account or Remote Access to enable and/or use.

**Comment by pizzaboy192** [comment]
Your Readme says that the facial recognition happens in the cloud though. That's the inaccurate part.

**Comment by AngellusMortis** [comment]
I do not really care. I am not interested in accepting any PRs from members of a community who have regularly harassed me and named called me because I do not want to "just enable Remote Access".

**Comment by pizzaboy192** [comment]
> I do not really care. I am not interested in accepting any PRs from members of a community who have regularly harassed me and named called me because I do not want to "just enable Remote Access".

I believe you've got me confused with someone else. I just occasionally update Home Assistant integrations I use and the libraries they rely on when I find quality of life improvements. I'm unaware of any community harassment and am sorry to hear that has happened to you.

**Comment by AngellusMortis** [comment]
If you are not the same pizzaboy, then I do apologize. There was a pizzaboy on the UI Discord, which is the community I am referring to. I have already removed the language from the README myself.

**Pull request closed without merging**
