### PR TITLE
Add the ability to toggle Color Night Vision

### PR DESCRIPTION
**Pull request by cmsimike**
Added support to control whether or not Color Night Vision is enabled.

Note: Two tests are currently failing. I tried a few things to get them passing but not sure what I'm missing. If you let me know what I need to do, I'm happy to update this PR.

This addresses: https://github.com/AngellusMortis/pyunifiprotect/issues/303

Fixes the previous PR (https://github.com/AngellusMortis/pyunifiprotect/pull/318) without a valid commit, and hoping it fixes the tests otherwise.

### CODE REVIEW

**Comment by cmsimike** [comment]
The tests seem to stop randomly but They Work On My Machine (tm)

**Comment by AngellusMortis** [comment]
Maybe you should actually [read what Github is saying](https://github.com/AngellusMortis/pyunifiprotect/actions/runs/6872370049/job/18690734668?pr=319) the issue is. There are no tests failing as they are not running/completing.

**Comment by cmsimike** [comment]
I was looking at 3.9 and 3.10
image
I'll get that updated.

**Comment by AngellusMortis** [comment]
"canceled". Meaning stopped without finishing. Run matrices can [automatically be stopped if one of the combinations fail](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#handling-failures).

**Review by AngellusMortis — APPROVED** [review]

**Pull request merged**
